#!/usr/bin/env ruby
Dir.chdir(File.dirname(__FILE__))

result = true
dir = 'fixtures'
Dir.foreach(dir) do |item|
  next if item == '.' or item == '..'
  file = "#{dir}/#{item}"

  print "#{item}: "

  expect = []
  open(file).each do |line|
    case line[0]
    when 'i'
      expect << line[1..-1].to_i
    when 'd'
      expect.delete(line[1..-1].to_i)
    else
      break
    end
  end
  expect = expect.sort.join("\n") + "\n"
  actual = `../bin < #{file} 2>/dev/null`
  result &&= expect == actual
  puts expect == actual ? "\e[32mOK\e[0m" : "\e[31mFailed\e[0m"

  next unless $?.success?
  next if expect == actual
  puts "  Expect: #{expect.inspect[0..65]}"
  puts "  Actual: #{actual.inspect[0..65]}"
  puts ''
end

exit result
