on: [push, pull_request]

strategy:
  matrix:
    compiler: ["gcc", "clang"]
    mode: ["", "debug"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: sudo apt-get install -y valgrind
    - run: make CC=${{ matrix.compiler }} ${{ matrix.mode }}
    - run: test/do
