on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler: ["gcc", "clang"]
        mode: ["", "debug"]
    steps:
    - uses: actions/checkout@v2
    - run: sudo apt-get install -y valgrind
    - run: make CC=${{ matrix.compiler }} ${{ matrix.mode }}
    - run: test/do
